In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd

In [2]:
blk = pd.read_csv("../csvs/htaindex_data_blkgrps_06.csv")
crimes = pd.read_csv("../csvs/crimes.csv")
schools = pd.read_csv("../csvs/new_district.csv")
bg_info = gpd.read_file("../tl_2017_06_bg/tl_2017_06_bg.shp")

In [3]:
blk.sort_values("blkgrp")

,blkgrp,blkgrps,population,households,land_acres,ht_ami,ht_80ami,ht_nmi,h_ami,h_80ami,...,emp_gravity,emp_ndx,block_size,intersection_density,avg_block_perimeter_meters,h_cost,median_smoc,median_gross_rent,pct_owner_occupied_hu,pct_renter_occupied_hu
1361,"""060014001001""",1.0,2952.0,1286.0,1703.63,76.0,92.0,112.0,57.0,71.0,...,44078.0,92.0,21.0,70.0,1334,3848.0,4001.0,2944.0,86.0,14.0
6528,"""060014002001""",1.0,1071.0,451.0,71.40,55.0,66.0,81.0,39.0,48.0,...,68635.0,93.0,3.0,385.0,511,2624.0,2984.0,1840.0,69.0,31.0
12850,"""060014002002""",1.0,913.0,381.0,73.76,54.0,65.0,79.0,38.0,48.0,...,71540.0,93.0,4.0,381.0,573,2583.0,3230.0,1699.0,58.0,42.0
7769,"""060014003001""",1.0,1414.0,487.0,65.65,60.0,72.0,88.0,44.0,55.0,...,70955.0,93.0,4.0,380.0,615,2964.0,4001.0,1343.0,61.0,39.0
13009,"""060014003002""",1.0,1259.0,701.0,66.50,43.0,51.0,62.0,28.0,36.0,...,87745.0,93.0,3.0,558.0,448,1936.0,3095.0,1286.0,36.0,64.0
13012,"""060014003003""",1.0,962.0,549.0,72.18,31.0,37.0,45.0,18.0,22.0,...,84942.0,93.0,2.0,674.0,458,1220.0,3000.0,824.0,18.0,82.0
13014,"""060014003004""",1.0,1742.0,752.0,68.80,44.0,52.0,64.0,28.0,35.0,...,79974.0,93.0,4.0,288.0,600,1915.0,2585.0,893.0,60.0,40.0
13008,"""060014004001""",1.0,1304.0,656.0,65.72,50.0,61.0,74.0,35.0,44.0,...,73478.0,93.0,3.0,260.0,491,2408.0,3629.0,1611.0,39.0,61.0
14741,"""060014004002""",1.0,1471.0,617.0,61.20,43.0,52.0,63.0,28.0,35.0,...,79696.0,93.0,3.0,493.0,446,1929.0,2860.0,1320.0,40.0,60.0
13051,"""060014004003""",1.0,1330.0,528.0,49.69,40.0,47.0,58.0,25.0,31.0,...,76818.0,93.0,2.0,498.0,425,1700.0,NaN,1700.0,34.0,66.0
13029,"""060014005001""",1.0,2362.0,1044.0,89.63,41.0,50.0,61.0,27.0,34.0,...,80448.0,94.0,3.0,410.0,450,1830.0,2543.0,1357.0,40.0,60.0
16466,"""060014005002""",1.0,718.0,285.0,33.55,41.0,49.0,59.0,26.0,33.0,...,83723.0,94.0,4.0,437.0,582,1794.0,2646.0,1500.0,26.0,74.0
15146,"""060014005003""",1.0,571.0,295.0,22.68,42.0,50.0,61.0,28.0,35.0,...,82368.0,94.0,3.0,339.0,490,1899.0,3233.0,1204.0,34.0,66.0
13266,"""060014006001""",1.0,1171.0,492.0,41.17,37.0,44.0,54.0,22.0,28.0,...,84419.0,93.0,3.0,389.0,443,1513.0,1875.0,1244.0,43.0,57.0
13268,"""060014006002""",1.0,494.0,209.0,32.44,30.0,36.0,43.0,14.0,18.0,...,89437.0,93.0,2.0,552.0,421,967.0,NaN,967.0,64.0,36.0
13256,"""060014007001""",1.0,1321.0,533.0,57.84,39.0,47.0,57.0,25.0,31.0,...,87313.0,94.0,2.0,610.0,328,1702.0,3040.0,1108.0,31.0,69.0
13263,"""060014007002""",1.0,1475.0,498.0,64.37,31.0,36.0,44.0,15.0,19.0,...,89553.0,94.0,2.0,457.0,398,1045.0,NaN,1045.0,41.0,59.0
13264,"""060014007003""",1.0,563.0,292.0,34.43,39.0,47.0,57.0,24.0,30.0,...,90956.0,94.0,2.0,502.0,359,1649.0,2417.0,1279.0,33.0,67.0
13261,"""060014007004""",1.0,1185.0,470.0,60.89,40.0,48.0,58.0,25.0,32.0,...,92730.0,94.0,2.0,535.0,366,1729.0,2804.0,1313.0,28.0,72.0
13270,"""060014008001""",1.0,1400.0,665.0,63.23,41.0,49.0,59.0,26.0,32.0,...,85420.0,94.0,2.0,420.0,393,1761.0,2283.0,1359.0,43.0,57.0
13271,"""060014008002""",1.0,816.0,395.0,52.16,39.0,46.0,56.0,24.0,30.0,...,88189.0,94.0,4.0,356.0,481,1632.0,2368.0,1303.0,31.0,69.0
13272,"""060014008003""",1.0,1311.0,512.0,57.09,40.0,48.0,59.0,26.0,32.0,...,87846.0,94.0,3.0,381.0,443,1736.0,2391.0,1390.0,35.0,65.0
13178,"""060014009001""",1.0,1398.0,635.0,54.13,40.0,48.0,58.0,25.0,32.0,...,89994.0,94.0,4.0,354.0,609,1720.0,2671.0,1273.0,32.0,68.0
13500,"""060014009002""",1.0,777.0,378.0,49.88,43.0,52.0,63.0,29.0,36.0,...,89122.0,94.0,3.0,377.0,485,1951.0,2438.0,1792.0,25.0,75.0
13502,"""060014010001""",1.0,1333.0,489.0,50.57,35.0,41.0,50.0,21.0,26.0,...,97155.0,94.0,2.0,606.0,458,1395.0,2072.0,1173.0,25.0,75.0
13503,"""060014010002""",1.0,949.0,352.0,35.82,43.0,52.0,63.0,29.0,36.0,...,100274.0,93.0,2.0,586.0,406,1965.0,1965.0,NaN,57.0,43.0
13467,"""060014010003""",1.0,1576.0,607.0,57.99,38.0,46.0,56.0,24.0,30.0,...,103034.0,94.0,2.0,417.0,408,1642.0,2274.0,1025.0,49.0,51.0
13094,"""060014010004""",1.0,549.0,256.0,34.93,32.0,38.0,46.0,19.0,24.0,...,106869.0,93.0,2.0,733.0,385,1292.0,NaN,1292.0,11.0,89.0
13506,"""060014010005""",1.0,739.0,343.0,53.56,30.0,36.0,44.0,18.0,22.0,...,112662.0,93.0,3.0,491.0,580,1203.0,NaN,1203.0,13.0,87.0
13507,"""060014010006""",1.0,841.0,486.0,50.56,30.0,35.0,43.0,17.0,21.0,...,104159.0,94.0,4.0,305.0,550,1135.0,NaN,1135.0,17.0,83.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22703,"""061150405001""",1.0,1418.0,390.0,203.36,52.0,60.0,49.0,24.0,30.0,...,5387.0,87.0,8.0,192.0,1101,985.0,901.0,1091.0,56.0,44.0
22704,"""061150405002""",1.0,1587.0,475.0,218.60,49.0,57.0,46.0,22.0,28.0,...,4668.0,87.0,18.0,88.0,1227,927.0,1286.0,743.0,34.0,66.0
22715,"""061150405003""",1.0,1248.0,373.0,192.32,47.0,55.0,44.0,20.0,26.0,...,4352.0,86.0,11.0,180.0,1171,850.0,NaN,850.0,38.0,62.0
22716,"""061150406001""",1.0,1903.0,497.0,348.72,62.0,73.0,58.0,32.0,40.0,...,4087.0,86.0,22.0,95.0,1347,1324.0,1518.0,897.0,69.0,31.0
8147,"""061150406002""",1.0,869.0,259.0,172.58,49.0,56.0,45.0,20.0,24.0,...,3890.0,86.0,12.0,163.0,880,812.0,NaN,812.0,56.0,44.0
22735,"""061150406003""",1.0,1069.0,390.0,185.19,53.0,61.0,49.0,23.0,29.0,...,3713.0,86.0,8.0,194.0,961,964.0,986.0,917.0,69.0,31.0
22736,"""061150406004""",1.0,1105.0,334.0,251.75,59.0,69.0,55.0,29.0,37.0,...,3691.0,86.0,18.0,102.0,1926,1213.0,1164.0,1273.0,55.0,45.0
22737,"""061150406005""",1.0,967.0,414.0,58.52,52.0,60.0,48.0,25.0,31.0,...,3264.0,85.0,3.0,405.0,475,1033.0,1181.0,781.0,63.0,37.0
8261,"""061150407001""",1.0,1904.0,582.0,2398.67,70.0,83.0,65.0,37.0,46.0,...,2778.0,85.0,96.0,23.0,1701,1536.0,1589.0,1350.0,78.0,22.0
22741,"""061150407002""",1.0,3292.0,911.0,983.66,64.0,74.0,59.0,31.0,39.0,...,3193.0,85.0,39.0,54.0,1614,1292.0,1340.0,661.0,93.0,7.0
10740,"""061150407003""",1.0,486.0,199.0,4059.37,63.0,74.0,59.0,30.0,37.0,...,2630.0,84.0,99.0,11.0,2310,1240.0,1240.0,NaN,82.0,18.0
158,"""061150407004""",1.0,3237.0,934.0,4774.98,79.0,94.0,73.0,46.0,58.0,...,2830.0,85.0,55.0,19.0,1747,1915.0,1988.0,1646.0,79.0,21.0
3891,"""061150407005""",1.0,3685.0,1118.0,11204.98,76.0,89.0,70.0,42.0,52.0,...,2265.0,84.0,146.0,11.0,3476,1730.0,1751.0,1603.0,86.0,14.0
20906,"""061150408001""",1.0,2734.0,855.0,11891.80,64.0,75.0,60.0,32.0,40.0,...,2238.0,84.0,71.0,15.0,2138,1344.0,1672.0,834.0,61.0,39.0
3878,"""061150408002""",1.0,392.0,152.0,4437.12,47.0,55.0,44.0,21.0,26.0,...,2124.0,83.0,70.0,23.0,1934,879.0,NaN,879.0,20.0,80.0
8423,"""061150408003""",1.0,1050.0,403.0,10704.06,67.0,80.0,63.0,35.0,43.0,...,2181.0,84.0,136.0,12.0,2562,1435.0,1466.0,1375.0,66.0,34.0
3919,"""061150409011""",1.0,1738.0,573.0,47072.44,68.0,81.0,63.0,36.0,45.0,...,1548.0,82.0,176.0,7.0,3251,1507.0,1594.0,1380.0,59.0,41.0
7066,"""061150409012""",1.0,1544.0,463.0,15934.76,64.0,74.0,59.0,32.0,40.0,...,2415.0,84.0,148.0,7.0,2799,1314.0,1510.0,748.0,74.0,26.0
1321,"""061150409021""",1.0,1223.0,251.0,22842.66,67.0,80.0,63.0,40.0,50.0,...,2130.0,84.0,86.0,12.0,1917,1646.0,NaN,1646.0,1.0,99.0
20918,"""061150409022""",1.0,18.0,4.0,1280.35,NaN,NaN,NaN,NaN,NaN,...,1833.0,83.0,131.0,21.0,2885,NaN,NaN,NaN,0.0,100.0
22750,"""061150409023""",1.0,449.0,177.0,1068.04,60.0,72.0,57.0,33.0,42.0,...,1718.0,82.0,29.0,39.0,1366,1389.0,NaN,1389.0,0.0,100.0
3156,"""061150410001""",1.0,1782.0,880.0,38439.31,84.0,100.0,78.0,50.0,63.0,...,1150.0,81.0,271.0,7.0,4143,2076.0,2076.0,NaN,85.0,15.0
8421,"""061150410002""",1.0,1939.0,707.0,9168.55,77.0,92.0,72.0,43.0,54.0,...,1286.0,82.0,316.0,10.0,4578,1780.0,1780.0,NaN,87.0,13.0
20861,"""061150410003""",1.0,1558.0,591.0,17081.81,78.0,93.0,72.0,44.0,56.0,...,1399.0,82.0,417.0,5.0,4240,1845.0,2068.0,1285.0,72.0,28.0
157,"""061150410004""",1.0,1275.0,473.0,14090.39,78.0,92.0,72.0,45.0,56.0,...,2458.0,85.0,172.0,4.0,3602,1851.0,2205.0,748.0,76.0,24.0
3923,"""061150410005""",1.0,434.0,219.0,37061.10,71.0,84.0,66.0,35.0,44.0,...,2273.0,85.0,378.0,3.0,5002,1467.0,NaN,1467.0,79.0,21.0
3861,"""061150411001""",1.0,863.0,484.0,73696.76,59.0,69.0,55.0,27.0,34.0,...,826.0,80.0,287.0,6.0,5275,1113.0,1207.0,890.0,70.0,30.0
139,"""061150411002""",1.0,1306.0,695.0,23265.62,53.0,62.0,49.0,21.0,26.0,...,1010.0,81.0,180.0,14.0,3026,873.0,NaN,873.0,59.0,41.0
20901,"""061150411003""",1.0,1250.0,583.0,20875.62,60.0,70.0,56.0,27.0,33.0,...,1022.0,81.0,278.0,13.0,3732,1101.0,1101.0,NaN,83.0,17.0
506,"""061150411004""",1.0,871.0,371.0,20371.98,60.0,70.0,55.0,26.0,33.0,...,990.0,81.0,304.0,11.0,3818,1088.0,1151.0,842.0,80.0,20.0

In [4]:
bg_info.sort_values("GEOID")

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,GEOID,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
2022,06,001,400100,1,060014001001,Block Group 1,G5030,S,6894340,0,+37.8676275,-122.2319460,"POLYGON ((-122.24692 37.885438, -122.246668 37..."
1816,06,001,400200,1,060014002001,Block Group 1,G5030,S,288960,0,+37.8497418,-122.2488605,"POLYGON ((-122.255084 37.846069, -122.254239 3..."
9929,06,001,400200,2,060014002002,Block Group 2,G5030,S,298490,0,+37.8465865,-122.2503095,"POLYGON ((-122.257923 37.842606, -122.257728 3..."
3609,06,001,400300,1,060014003001,Block Group 1,G5030,S,265695,0,+37.8439848,-122.2486668,"POLYGON ((-122.251857 37.844746, -122.251781 3..."
10173,06,001,400300,2,060014003002,Block Group 2,G5030,S,269098,0,+37.8362550,-122.2516875,"POLYGON ((-122.262305 37.837859, -122.262187 3..."
10174,06,001,400300,3,060014003003,Block Group 3,G5030,S,292123,0,+37.8404618,-122.2597461,"POLYGON ((-122.265631 37.837636, -122.265565 3..."
10175,06,001,400300,4,060014003004,Block Group 4,G5030,S,278413,0,+37.8402856,-122.2541313,"POLYGON ((-122.258074 37.838292, -122.257814 3..."
10176,06,001,400400,1,060014004001,Block Group 1,G5030,S,265952,0,+37.8500893,-122.2549822,"POLYGON ((-122.257274 37.853298, -122.257058 3..."
12112,06,001,400400,2,060014004002,Block Group 2,G5030,S,247682,0,+37.8448409,-122.2590489,"POLYGON ((-122.261826 37.841623, -122.261805 3..."
10198,06,001,400400,3,060014004003,Block Group 3,G5030,S,201094,0,+37.8501240,-122.2587560,"POLYGON ((-122.260995 37.847379, -122.260925 3..."
10199,06,001,400500,1,060014005001,Block Group 1,G5030,S,362733,0,+37.8488953,-122.2631970,"POLYGON ((-122.266128 37.852009, -122.266066 3..."
14221,06,001,400500,2,060014005002,Block Group 2,G5030,S,135779,0,+37.8465131,-122.2670453,"POLYGON ((-122.269409 37.848107, -122.268958 3..."
12504,06,001,400500,3,060014005003,Block Group 3,G5030,S,91795,0,+37.8501417,-122.2673478,"POLYGON ((-122.269507 37.848582, -122.26937 37..."
10540,06,001,400600,1,060014006001,Block Group 1,G5030,S,166589,0,+37.8432924,-122.2645380,"POLYGON ((-122.26807 37.844136, -122.267856 37..."
10541,06,001,400600,2,060014006002,Block Group 2,G5030,S,131267,0,+37.8403392,-122.2653325,"POLYGON ((-122.267562 37.841672, -122.267013 3..."
10542,06,001,400700,1,060014007001,Block Group 1,G5030,S,234052,0,+37.8453891,-122.2734437,"POLYGON ((-122.278078 37.847326, -122.277885 3..."
10543,06,001,400700,2,060014007002,Block Group 2,G5030,S,260479,0,+37.8426023,-122.2723644,"POLYGON ((-122.277032 37.843286, -122.277026 3..."
10544,06,001,400700,3,060014007003,Block Group 3,G5030,S,139344,0,+37.8403773,-122.2719191,"POLYGON ((-122.27658 37.84067599999999, -122.2..."
10546,06,001,400700,4,060014007004,Block Group 4,G5030,S,246428,0,+37.8382287,-122.2715499,"POLYGON ((-122.276311 37.83926599999999, -122...."
10547,06,001,400800,1,060014008001,Block Group 1,G5030,S,254139,0,+37.8481128,-122.2848711,"POLYGON ((-122.28873 37.849962, -122.286247 37..."
10548,06,001,400800,2,060014008002,Block Group 2,G5030,S,211070,0,+37.8452810,-122.2825720,"POLYGON ((-122.287499 37.845772, -122.287158 3..."
10549,06,001,400800,3,060014008003,Block Group 3,G5030,S,231031,0,+37.8427279,-122.2825214,"POLYGON ((-122.286714 37.843345, -122.286543 3..."
10550,06,001,400900,1,060014009001,Block Group 1,G5030,S,219037,0,+37.8406240,-122.2795236,"POLYGON ((-122.283186 37.840978, -122.283062 3..."
10876,06,001,400900,2,060014009002,Block Group 2,G5030,S,201840,0,+37.8382619,-122.2810688,"POLYGON ((-122.285576 37.839778, -122.284753 3..."
10877,06,001,401000,1,060014010001,Block Group 1,G5030,S,204667,0,+37.8358374,-122.2696518,"POLYGON ((-122.275607 37.83643, -122.275638 37..."
10878,06,001,401000,2,060014010002,Block Group 2,G5030,S,144974,0,+37.8340002,-122.2711306,"POLYGON ((-122.276146 37.83496, -122.275896 37..."
10883,06,001,401000,3,060014010003,Block Group 3,G5030,S,234693,0,+37.8322037,-122.2724161,"POLYGON ((-122.277168 37.832297, -122.276943 3..."
10884,06,001,401000,4,060014010004,Block Group 4,G5030,S,141375,0,+37.8291541,-122.2692510,"POLYGON ((-122.271675 37.827824, -122.271535 3..."
10885,06,001,401000,5,060014010005,Block Group 5,G5030,S,216486,0,+37.8266786,-122.2729236,"POLYGON ((-122.278707 37.827151, -122.278579 3..."
10886,06,001,401000,6,060014010006,Block Group 6,G5030,S,202138,0,+37.8297483,-122.2748931,"POLYGON ((-122.278463 37.828864, -122.278369 3..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22899,06,115,040500,1,061150405001,Block Group 1,G5030,S,825140,0,+39.1073153,-121.5567879,"POLYGON ((-121.563114 39.113103, -121.562864 3..."
22900,06,115,040500,2,061150405002,Block Group 2,G5030,S,884707,0,+39.0977118,-121.5558886,"POLYGON ((-121.560826 39.104537, -121.560695 3..."
22908,06,115,040500,3,061150405003,Block Group 3,G5030,S,778291,0,+39.0960458,-121.5475208,"POLYGON ((-121.551729 39.091992, -121.551692 3..."
22909,06,115,040600,1,061150406001,Block Group 1,G5030,S,1411208,0,+39.0849596,-121.5567372,"POLYGON ((-121.561379 39.077559, -121.561372 3..."
4192,06,115,040600,2,061150406002,Block Group 2,G5030,S,697595,0,+39.0876155,-121.5472231,"POLYGON ((-121.551979 39.085368, -121.551973 3..."
22949,06,115,040600,3,061150406003,Block Group 3,G5030,S,750247,0,+39.0816352,-121.5460538,"POLYGON ((-121.551934 39.077302, -121.551915 3..."
22950,06,115,040600,4,061150406004,Block Group 4,G5030,S,1018643,0,+39.0835235,-121.5366658,"POLYGON ((-121.545537 39.09835899999999, -121...."
22951,06,115,040600,5,061150406005,Block Group 5,G5030,S,236644,0,+39.0794743,-121.5336689,"POLYGON ((-121.537592 39.077845, -121.537539 3..."
4311,06,115,040700,1,061150407001,Block Group 1,G5030,S,9708409,0,+39.0444736,-121.5681382,"POLYGON ((-121.579022 39.057039, -121.579015 3..."
22952,06,115,040700,2,061150407002,Block Group 2,G5030,S,3979424,0,+39.0666788,-121.5517340,"POLYGON ((-121.561538 39.070599, -121.561508 3..."
7382,06,115,040700,3,061150407003,Block Group 3,G5030,S,16426837,120246,+39.0601318,-121.5269595,"POLYGON ((-121.55998 39.05524399999999, -121.5..."
22446,06,115,040700,4,061150407004,Block Group 4,G5030,S,19331656,403540,+39.0368432,-121.5858940,"POLYGON ((-121.61025 39.056907, -121.610209 39..."
20450,06,115,040700,5,061150407005,Block Group 5,G5030,S,45328513,881913,+38.9955396,-121.5454748,"POLYGON ((-121.589044 38.991522, -121.588379 3..."
20260,06,115,040800,1,061150408001,Block Group 1,G5030,S,48119986,17378,+39.0274063,-121.4760398,"POLYGON ((-121.515524 39.030637, -121.515324 3..."
20257,06,115,040800,2,061150408002,Block Group 2,G5030,S,17965728,110938,+39.0360212,-121.3729194,"POLYGON ((-121.426272 39.010203, -121.426091 3..."
4492,06,115,040800,3,061150408003,Block Group 3,G5030,S,43315702,0,+39.0496085,-121.4105794,"POLYGON ((-121.471538 39.040692, -121.471499 3..."
20253,06,115,040901,1,061150409011,Block Group 1,G5030,S,199153381,4473096,+39.1570528,-121.3701062,"POLYGON ((-121.583383 39.136205, -121.583189 3..."
4191,06,115,040901,2,061150409012,Block Group 2,G5030,S,64499186,0,+39.1055051,-121.4867718,"POLYGON ((-121.55755 39.113275, -121.554251 39..."
20264,06,115,040902,1,061150409021,Block Group 1,G5030,S,84113462,240059,+39.1191804,-121.3995270,"POLYGON ((-121.477218 39.133333, -121.477085 3..."
20258,06,115,040902,2,061150409022,Block Group 2,G5030,S,5181394,0,+39.0900768,-121.3514938,"POLYGON ((-121.367746 39.080711, -121.367649 3..."
22958,06,115,040902,3,061150409023,Block Group 3,G5030,S,4322222,0,+39.1030915,-121.3284998,"POLYGON ((-121.338706 39.088165, -121.33863 39..."
20263,06,115,041000,1,061150410001,Block Group 1,G5030,S,155372935,5206424,+39.2923343,-121.3205968,"POLYGON ((-121.414091 39.22814, -121.414044 39..."
4493,06,115,041000,2,061150410002,Block Group 2,G5030,S,37103820,0,+39.3252056,-121.3948579,"POLYGON ((-121.469474 39.333476, -121.469002 3..."
20255,06,115,041000,3,061150410003,Block Group 3,G5030,S,69127702,35607,+39.2661888,-121.4453728,"POLYGON ((-121.510877 39.230987, -121.510863 3..."
20254,06,115,041000,4,061150410004,Block Group 4,G5030,S,56811849,717754,+39.1871939,-121.5467990,"POLYGON ((-121.601279 39.219171, -121.600937 3..."
20256,06,115,041000,5,061150410005,Block Group 5,G5030,S,149981083,967541,+39.2686837,-121.5454285,"POLYGON ((-121.636368 39.246076, -121.636288 3..."
4402,06,115,041100,1,061150411001,Block Group 1,G5030,S,298240469,16529900,+39.4828724,-121.1090654,"POLYGON ((-121.278919 39.497727, -121.278805 3..."
4494,06,115,041100,2,061150411002,Block Group 2,G5030,S,94152564,550493,+39.3656565,-121.2369173,"POLYGON ((-121.324069 39.362824, -121.323305 3..."
20259,06,115,041100,3,061150411003,Block Group 3,G5030,S,84480720,0,+39.4235869,-121.2211422,"POLYGON ((-121.284109 39.461376, -121.284062 3..."
20261,06,115,041100,4,061150411004,Block Group 4,G5030,S,82442537,0,+39.4258061,-121.3206670,"POLYGON ((-121.372573 39.373579, -121.372534 3..."

In [5]:
blk[blk["blkgrp"] == "\"060014001001\""]

,blkgrp,blkgrps,population,households,land_acres,ht_ami,ht_80ami,ht_nmi,h_ami,h_80ami,...,emp_gravity,emp_ndx,block_size,intersection_density,avg_block_perimeter_meters,h_cost,median_smoc,median_gross_rent,pct_owner_occupied_hu,pct_renter_occupied_hu
1361,"""060014001001""",1.0,2952.0,1286.0,1703.63,76.0,92.0,112.0,57.0,71.0,...,44078.0,92.0,21.0,70.0,1334,3848.0,4001.0,2944.0,86.0,14.0

In [6]:
type(bg_info["GEOID"][1])

str

In [7]:
blk["blkgrp"] = blk['blkgrp'].apply(lambda k: k[1:-1])

In [8]:
blk.head()

,blkgrp,blkgrps,population,households,land_acres,ht_ami,ht_80ami,ht_nmi,h_ami,h_80ami,...,emp_gravity,emp_ndx,block_size,intersection_density,avg_block_perimeter_meters,h_cost,median_smoc,median_gross_rent,pct_owner_occupied_hu,pct_renter_occupied_hu
0,060371190025,1.0,1266.0,344.0,69.97,57.0,67.0,62.0,33.0,42.0,...,43925.0,93.0,5.0,239.0,730,1684.0,1677.0,1690.0,49.0,51.0
1,060373200001,1.0,0.0,0.0,298.18,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2641,NaN,NaN,NaN,NaN,NaN
2,060371240001,1.0,1546.0,472.0,65.40,82.0,98.0,90.0,58.0,73.0,...,74872.0,95.0,11.0,196.0,970,2940.0,3659.0,1854.0,60.0,40.0
3,060530115021,1.0,1463.0,573.0,160871.45,60.0,72.0,64.0,29.0,37.0,...,984.0,82.0,570.0,2.0,5838,1438.0,1985.0,841.0,52.0,48.0
4,060770047042,1.0,1152.0,401.0,20432.53,85.0,103.0,84.0,51.0,64.0,...,2710.0,85.0,378.0,3.0,4667,2275.0,2530.0,639.0,87.0,13.0

In [9]:
len(bg_info)

23212

In [10]:
len(blk)

23190

In [11]:
test = pd.merge(blk, bg_info[["GEOID", "COUNTYFP", "geometry"]], how='left', left_on="blkgrp", right_on='GEOID')

In [12]:
test.head()

,blkgrp,blkgrps,population,households,land_acres,ht_ami,ht_80ami,ht_nmi,h_ami,h_80ami,...,intersection_density,avg_block_perimeter_meters,h_cost,median_smoc,median_gross_rent,pct_owner_occupied_hu,pct_renter_occupied_hu,GEOID,COUNTYFP,geometry
0,060371190025,1.0,1266.0,344.0,69.97,57.0,67.0,62.0,33.0,42.0,...,239.0,730,1684.0,1677.0,1690.0,49.0,51.0,060371190025,037,"POLYGON ((-118.440116 34.252946, -118.438685 3..."
1,060373200001,1.0,0.0,0.0,298.18,NaN,NaN,NaN,NaN,NaN,...,NaN,2641,NaN,NaN,NaN,NaN,NaN,060373200001,037,"POLYGON ((-118.362151 34.139028, -118.361209 3..."
2,060371240001,1.0,1546.0,472.0,65.40,82.0,98.0,90.0,58.0,73.0,...,196.0,970,2940.0,3659.0,1854.0,60.0,40.0,060371240001,037,"POLYGON ((-118.413011 34.168292, -118.412716 3..."
3,060530115021,1.0,1463.0,573.0,160871.45,60.0,72.0,64.0,29.0,37.0,...,2.0,5838,1438.0,1985.0,841.0,52.0,48.0,060530115021,053,"POLYGON ((-121.941403 36.48042, -121.941438 36..."
4,060770047042,1.0,1152.0,401.0,20432.53,85.0,103.0,84.0,51.0,64.0,...,3.0,4667,2275.0,2530.0,639.0,87.0,13.0,060770047042,077,"POLYGON ((-121.150872 38.11777, -121.150871 38..."

In [13]:
test.columns

Index(['blkgrp', 'blkgrps', 'population', 'households', 'land_acres', 'ht_ami',
       'ht_80ami', 'ht_nmi', 'h_ami', 'h_80ami', 'h_nmi', 't_ami', 't_80ami',
       't_nmi', 'co2_per_hh_local', 'co2_per_acre_local', 'autos_per_hh_ami',
       'autos_per_hh_80ami', 'autos_per_hh_nmi', 'vmt_per_hh_ami',
       'vmt_per_hh_80ami', 'vmt_per_hh_nmi', 'pct_transit_commuters_ami',
       'pct_transit_commuters_80ami', 'pct_transit_commuters_nmi',
       't_cost_ami', 't_cost_80ami', 't_cost_nmi', 'auto_ownership_cost_ami',
       'auto_ownership_cost_80ami', 'auto_ownership_cost_nmi', 'vmt_cost_ami',
       'vmt_cost_80ami', 'vmt_cost_nmi', 'transit_cost_ami',
       'transit_cost_80ami', 'transit_cost_nmi', 'transit_trips_ami',
       'transit_trips_80ami', 'transit_trips_nmi', 'compact_ndx',
       'emp_ovrll_ndx', 'res_density', 'gross_hh_density', 'hh_gravity',
       'frac_sfd', 'emp_gravity', 'emp_ndx', 'block_size',
       'intersection_density', 'avg_block_perimeter_meters', 'h_cost',
       'median_smoc', 'median_gross_rent', 'pct_owner_occupied_hu',
       'pct_renter_occupied_hu', 'GEOID', 'COUNTYFP', 'geometry'],
      dtype='object')

In [14]:
places = gpd.read_file("../tl_2017_06_place/tl_2017_06_place.shp")
places.head()

,STATEFP,PLACEFP,PLACENS,GEOID,NAME,NAMELSAD,LSAD,CLASSFP,PCICBSA,PCINECTA,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,06,66140,02411785,0666140,San Fernando,San Fernando city,25,C1,N,N,G4110,A,6148697,0,+34.2886519,-118.4362413,"POLYGON ((-118.456008 34.284903, -118.454141 3..."
1,06,14190,02409487,0614190,Cloverdale,Cloverdale city,25,C1,N,N,G4110,A,7863864,59201,+38.7959624,-123.0153700,"POLYGON ((-123.035115 38.787005, -123.035093 3..."
2,06,16560,02410240,0616560,Cotati,Cotati city,25,C1,N,N,G4110,A,4869007,8380,+38.3284920,-122.7100491,"POLYGON ((-122.729598 38.333486, -122.729512 3..."
3,06,65042,02411779,0665042,San Buenaventura (Ventura),San Buenaventura (Ventura) city,25,C1,Y,N,G4110,A,56500370,27033717,+34.2677796,-119.2542062,"(POLYGON ((-119.297103 34.344633, -119.297012 ..."
4,06,30014,02410601,0630014,Glendora,Glendora city,25,C1,N,N,G4110,A,50634794,400124,+34.1449667,-117.8476672,"POLYGON ((-117.891093 34.14581, -117.89064 34...."

In [15]:
len(set(places.NAME))

1505

In [16]:
len(places.NAME)

1522

In [17]:
counties = gpd.read_file("../tl_2017_us_county/tl_2017_us_county.shp")
counties.head()

,STATEFP,COUNTYFP,COUNTYNS,GEOID,NAME,NAMELSAD,LSAD,CLASSFP,MTFCC,CSAFP,CBSAFP,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,31,039,00835841,31039,Cuming,Cuming County,06,H1,G4020,,,,A,1477641638,10701538,+41.9158651,-096.7885168,"POLYGON ((-97.019516 42.004097, -97.019519 42...."
1,53,069,01513275,53069,Wahkiakum,Wahkiakum County,06,H1,G4020,,,,A,680956787,61588406,+46.2946377,-123.4244583,"POLYGON ((-123.436394 46.238197, -123.447592 4..."
2,35,011,00933054,35011,De Baca,De Baca County,06,H1,G4020,,,,A,6016761648,29147345,+34.3592729,-104.3686961,"POLYGON ((-104.567387 33.997566, -104.567717 3..."
3,31,109,00835876,31109,Lancaster,Lancaster County,06,H1,G4020,339,30700,,A,2169252486,22867561,+40.7835474,-096.6886584,"POLYGON ((-96.91059899999999 40.958407, -96.91..."
4,31,129,00835886,31129,Nuckolls,Nuckolls County,06,H1,G4020,,,,A,1489645186,1718484,+40.1764918,-098.0468422,"POLYGON ((-98.27366699999999 40.089399, -98.27..."

In [18]:
ca_counties = counties[counties['STATEFP'] == '06']
ca_counties.drop("geometry", axis=1, inplace=True)
ca_counties.head()

/Users/kanamishra/anaconda3/lib/python3.5/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,STATEFP,COUNTYFP,COUNTYNS,GEOID,NAME,NAMELSAD,LSAD,CLASSFP,MTFCC,CSAFP,CBSAFP,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON
8,06,091,00277310,06091,Sierra,Sierra County,06,H1,G4020,,,,A,2468694586,23299110,+39.5769252,-120.5219926
325,06,067,00277298,06067,Sacramento,Sacramento County,06,H1,G4020,472,40900,,A,2499039655,76217822,+38.4500161,-121.3404408
329,06,083,00277306,06083,Santa Barbara,Santa Barbara County,06,H1,G4020,,42200,,A,7084000622,2729814515,+34.5370572,-120.0399729
346,06,009,01675885,06009,Calaveras,Calaveras County,06,H1,G4020,,,,A,2641829199,43797662,+38.1838996,-120.5614415
394,06,111,00277320,06111,Ventura,Ventura County,06,H1,G4020,348,37100,,A,4773302741,946030569,+34.3587415,-119.1331432

In [19]:
add_county_to_ht_bg = pd.merge(test, ca_counties[["NAME", "COUNTYFP"]], how='left', on='COUNTYFP')

In [20]:
add_county_to_ht_bg.head()

,blkgrp,blkgrps,population,households,land_acres,ht_ami,ht_80ami,ht_nmi,h_ami,h_80ami,...,avg_block_perimeter_meters,h_cost,median_smoc,median_gross_rent,pct_owner_occupied_hu,pct_renter_occupied_hu,GEOID,COUNTYFP,geometry,NAME
0,060371190025,1.0,1266.0,344.0,69.97,57.0,67.0,62.0,33.0,42.0,...,730,1684.0,1677.0,1690.0,49.0,51.0,060371190025,037,"POLYGON ((-118.440116 34.252946, -118.438685 3...",Los Angeles
1,060373200001,1.0,0.0,0.0,298.18,NaN,NaN,NaN,NaN,NaN,...,2641,NaN,NaN,NaN,NaN,NaN,060373200001,037,"POLYGON ((-118.362151 34.139028, -118.361209 3...",Los Angeles
2,060371240001,1.0,1546.0,472.0,65.40,82.0,98.0,90.0,58.0,73.0,...,970,2940.0,3659.0,1854.0,60.0,40.0,060371240001,037,"POLYGON ((-118.413011 34.168292, -118.412716 3...",Los Angeles
3,060530115021,1.0,1463.0,573.0,160871.45,60.0,72.0,64.0,29.0,37.0,...,5838,1438.0,1985.0,841.0,52.0,48.0,060530115021,053,"POLYGON ((-121.941403 36.48042, -121.941438 36...",Monterey
4,060770047042,1.0,1152.0,401.0,20432.53,85.0,103.0,84.0,51.0,64.0,...,4667,2275.0,2530.0,639.0,87.0,13.0,060770047042,077,"POLYGON ((-121.150872 38.11777, -121.150871 38...",San Joaquin

In [21]:
add_county_to_ht_bg.drop(["GEOID", "COUNTYFP"], axis = 1, inplace=True)
add_county_to_ht_bg.rename(columns={"blkgrp":"GEOID"}, inplace=True)
add_county_to_ht_bg.head()

,GEOID,blkgrps,population,households,land_acres,ht_ami,ht_80ami,ht_nmi,h_ami,h_80ami,...,block_size,intersection_density,avg_block_perimeter_meters,h_cost,median_smoc,median_gross_rent,pct_owner_occupied_hu,pct_renter_occupied_hu,geometry,NAME
0,060371190025,1.0,1266.0,344.0,69.97,57.0,67.0,62.0,33.0,42.0,...,5.0,239.0,730,1684.0,1677.0,1690.0,49.0,51.0,"POLYGON ((-118.440116 34.252946, -118.438685 3...",Los Angeles
1,060373200001,1.0,0.0,0.0,298.18,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2641,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-118.362151 34.139028, -118.361209 3...",Los Angeles
2,060371240001,1.0,1546.0,472.0,65.40,82.0,98.0,90.0,58.0,73.0,...,11.0,196.0,970,2940.0,3659.0,1854.0,60.0,40.0,"POLYGON ((-118.413011 34.168292, -118.412716 3...",Los Angeles
3,060530115021,1.0,1463.0,573.0,160871.45,60.0,72.0,64.0,29.0,37.0,...,570.0,2.0,5838,1438.0,1985.0,841.0,52.0,48.0,"POLYGON ((-121.941403 36.48042, -121.941438 36...",Monterey
4,060770047042,1.0,1152.0,401.0,20432.53,85.0,103.0,84.0,51.0,64.0,...,378.0,3.0,4667,2275.0,2530.0,639.0,87.0,13.0,"POLYGON ((-121.150872 38.11777, -121.150871 38...",San Joaquin

In [22]:
add_county_to_ht_bg.columns

Index(['GEOID', 'blkgrps', 'population', 'households', 'land_acres', 'ht_ami',
       'ht_80ami', 'ht_nmi', 'h_ami', 'h_80ami', 'h_nmi', 't_ami', 't_80ami',
       't_nmi', 'co2_per_hh_local', 'co2_per_acre_local', 'autos_per_hh_ami',
       'autos_per_hh_80ami', 'autos_per_hh_nmi', 'vmt_per_hh_ami',
       'vmt_per_hh_80ami', 'vmt_per_hh_nmi', 'pct_transit_commuters_ami',
       'pct_transit_commuters_80ami', 'pct_transit_commuters_nmi',
       't_cost_ami', 't_cost_80ami', 't_cost_nmi', 'auto_ownership_cost_ami',
       'auto_ownership_cost_80ami', 'auto_ownership_cost_nmi', 'vmt_cost_ami',
       'vmt_cost_80ami', 'vmt_cost_nmi', 'transit_cost_ami',
       'transit_cost_80ami', 'transit_cost_nmi', 'transit_trips_ami',
       'transit_trips_80ami', 'transit_trips_nmi', 'compact_ndx',
       'emp_ovrll_ndx', 'res_density', 'gross_hh_density', 'hh_gravity',
       'frac_sfd', 'emp_gravity', 'emp_ndx', 'block_size',
       'intersection_density', 'avg_block_perimeter_meters', 'h_cost',
       'median_smoc', 'median_gross_rent', 'pct_owner_occupied_hu',
       'pct_renter_occupied_hu', 'geometry', 'NAME'],
      dtype='object')

In [23]:
blk.columns

Index(['blkgrp', 'blkgrps', 'population', 'households', 'land_acres', 'ht_ami',
       'ht_80ami', 'ht_nmi', 'h_ami', 'h_80ami', 'h_nmi', 't_ami', 't_80ami',
       't_nmi', 'co2_per_hh_local', 'co2_per_acre_local', 'autos_per_hh_ami',
       'autos_per_hh_80ami', 'autos_per_hh_nmi', 'vmt_per_hh_ami',
       'vmt_per_hh_80ami', 'vmt_per_hh_nmi', 'pct_transit_commuters_ami',
       'pct_transit_commuters_80ami', 'pct_transit_commuters_nmi',
       't_cost_ami', 't_cost_80ami', 't_cost_nmi', 'auto_ownership_cost_ami',
       'auto_ownership_cost_80ami', 'auto_ownership_cost_nmi', 'vmt_cost_ami',
       'vmt_cost_80ami', 'vmt_cost_nmi', 'transit_cost_ami',
       'transit_cost_80ami', 'transit_cost_nmi', 'transit_trips_ami',
       'transit_trips_80ami', 'transit_trips_nmi', 'compact_ndx',
       'emp_ovrll_ndx', 'res_density', 'gross_hh_density', 'hh_gravity',
       'frac_sfd', 'emp_gravity', 'emp_ndx', 'block_size',
       'intersection_density', 'avg_block_perimeter_meters', 'h_cost',
       'median_smoc', 'median_gross_rent', 'pct_owner_occupied_hu',
       'pct_renter_occupied_hu'],
      dtype='object')

In [24]:
crimes.drop("Unnamed: 0", axis=1, inplace=True)
crimes.head()

      County  Violent_sum  Property_sum
0    Alameda        10127         59744
1     Alpine            6            34
2     Amador           92           669
3      Butte          790          7307
4  Calaveras          178           656

In [25]:
schools_by_county = schools[['County', 'Rank score (2017)']].groupby("County").aggregate(np.nanmean).reset_index()
schools_by_county.head()

/Users/kanamishra/anaconda3/lib/python3.5/site-packages/pandas/core/groupby.py:842: RuntimeWarning: Mean of empty slice
  f = lambda x: func(x, *args, **kwargs)

      County  Rank score (2017)
0    Alameda           0.625222
1     Alpine           0.103000
2     Amador           0.365000
3      Butte           0.456600
4  Calaveras           0.510000

In [26]:
crimeschools = pd.merge(crimes, schools_by_county, on="County")
crimeschools.head()

      County  Violent_sum  Property_sum  Rank score (2017)
0    Alameda        10127         59744           0.625222
1     Alpine            6            34           0.103000
2     Amador           92           669           0.365000
3      Butte          790          7307           0.456600
4  Calaveras          178           656           0.510000

In [27]:
bg_full = pd.merge(add_county_to_ht_bg, crimeschools, how = 'left', left_on='NAME', right_on='County')
bg_full.drop("NAME", axis=1, inplace=True)
bg_full.head()

,GEOID,blkgrps,population,households,land_acres,ht_ami,ht_80ami,ht_nmi,h_ami,h_80ami,...,h_cost,median_smoc,median_gross_rent,pct_owner_occupied_hu,pct_renter_occupied_hu,geometry,County,Violent_sum,Property_sum,Rank score (2017)
0,060371190025,1.0,1266.0,344.0,69.97,57.0,67.0,62.0,33.0,42.0,...,1684.0,1677.0,1690.0,49.0,51.0,"POLYGON ((-118.440116 34.252946, -118.438685 3...",Los Angeles,56351,252224,0.582235
1,060373200001,1.0,0.0,0.0,298.18,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-118.362151 34.139028, -118.361209 3...",Los Angeles,56351,252224,0.582235
2,060371240001,1.0,1546.0,472.0,65.40,82.0,98.0,90.0,58.0,73.0,...,2940.0,3659.0,1854.0,60.0,40.0,"POLYGON ((-118.413011 34.168292, -118.412716 3...",Los Angeles,56351,252224,0.582235
3,060530115021,1.0,1463.0,573.0,160871.45,60.0,72.0,64.0,29.0,37.0,...,1438.0,1985.0,841.0,52.0,48.0,"POLYGON ((-121.941403 36.48042, -121.941438 36...",Monterey,1822,10396,0.400421
4,060770047042,1.0,1152.0,401.0,20432.53,85.0,103.0,84.0,51.0,64.0,...,2275.0,2530.0,639.0,87.0,13.0,"POLYGON ((-121.150872 38.11777, -121.150871 38...",San Joaquin,6005,22629,0.462733

In [28]:
# bg_full.to_csv("bg.csv")

In [29]:
bg_full[bg_full["GEOID"] == "061130101024"]

,GEOID,blkgrps,population,households,land_acres,ht_ami,ht_80ami,ht_nmi,h_ami,h_80ami,...,h_cost,median_smoc,median_gross_rent,pct_owner_occupied_hu,pct_renter_occupied_hu,geometry,County,Violent_sum,Property_sum,Rank score (2017)
22916,061130101024,1.0,2914.0,1063.0,194.3,40.0,46.0,43.0,18.0,23.0,...,917.0,961.0,881.0,45.0,55.0,"POLYGON ((-121.542375 38.591286, -121.542095 3...",Yolo,639,5368,0.4644

In [57]:
! ls

CA_Counties                   myscript.js
README.md                     myscript_school_everything.js
bg.csv                        old_renditions
block_group_trial.ipynb       style.css
csvs                          temp
everything_school.js          tl_2017_06_bg
hta_ca.js                     tl_2017_06_place
index.html                    tl_2017_06_tract
index_school_everything.html  tl_2017_us_county
ipynbs

In [30]:
import json

In [35]:
with open("../bg_topo.json", 'r') as file:
    js = file.read()
temp = json.loads(js)

In [39]:
len(temp['arcs'])

63417

In [51]:
for i in temp.keys():
    print(i,len(temp[i]))

objects 1
transform 2
type 8
arcs 63417

23190

In [59]:
print(temp["objects"])

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

In [48]:
temp['arcs'][0]

[[1634638, 41332],
 [24, 101],
 [36, 84],
 [46, 113],
 [49, 110],
 [62, 137],
 [49, 83],
 [7, 11],
 [40, 58],
 [2, 3],
 [103, 157],
 [80, 130],
 [131, 254],
 [111, 142],
 [102, 129],
 [132, 181],
 [110, 172],
 [70, 112],
 [190, 231],
 [80, 115],
 [80, 122],
 [50, 73],
 [34, 50],
 [70, 132],
 [72, 105],
 [70, 111],
 [74, 134],
 [47, 66],
 [20, 39],
 [4, 6],
 [11, 19],
 [3, 7],
 [14, 6],
 [41, 19],
 [13, 7],
 [43, 15],
 [50, 34],
 [22, 32],
 [8, 12],
 [28, 48],
 [19, 69],
 [4, 20],
 [13, 59],
 [1, 7],
 [9, 39],
 [-6, 45],
 [-1, 62],
 [1, 6],
 [-20, 87],
 [-10, 40],
 [-14, 53],
 [-35, 111],
 [-9, 29],
 [-16, 47],
 [-16, 41],
 [-12, 29],
 [-29, 59],
 [-4, 9],
 [-24, 68],
 [-36, 84],
 [-28, 62],
 [-11, 25],
 [-16, 47],
 [-26, 43],
 [-16, 73],
 [-13, 57],
 [-3, 10],
 [-4, 33],
 [-6, 45],
 [0, 61],
 [3, 37],
 [-4, 97],
 [11, 129],
 [4, 122],
 [3, 36],
 [6, 64],
 [7, 72],
 [1, 31],
 [1, 63],
 [0, 12],
 [3, 39],
 [6, 38],
 [5, 23],
 [20, 67],
 [17, 43],
 [9, 21],
 [41, 74],
 [39, 56],
 [8, 9],
 [26, 32],
 [10, 11],
 [79, 68],
 [17, 13],
 [579, 364],
 [25, 15],
 [221, 115],
 [13, 6],
 [7, 2],
 [3, 3],
 [5, 4],
 [5, 3],
 [10, 6],
 [8, 5],
 [12, 10],
 [5, 6],
 [6, 4],
 [7, 2],
 [60, 43],
 [5, 5],
 [93, 109],
 [60, 117]]